### PR TITLE
Add reschedule rake task experimental

### PR DESCRIPTION
**Pull request by CallumD**
Do not merge also please only look at the last commit. This PR is an experimental branch in relation to issue #20

### CODE REVIEW

**Comment by CallumD** [comment]
@alikhajeh1 @smcgivern I have reworked this a bit. Can you take a look and let me know your thoughts?

**Comment by smcgivern** [comment]
LGTM.

**Comment by alikhajeh1** [comment]
+1, like the `:count => 0` trick

**Comment by CallumD** [comment]
closes https://github.com/rightscale/scheduled_job/pull/21

**Pull request merged**
